rickklaasboer/wego-overseer

src/commands/SpooktoberCommand.ts
giphy guidelines require this 🤷‍♂️
=> fix: giphy attribution

src/events/BangerEvent.ts, src/index.ts
Added BangerEvent with proper capitalisation
=> Feat: BangerEvent

src/events/IAmDadEvent.ts
Closes https://github.com/rickklaasboer/wego-overseer/issues/18
Bot doesn't reply to just: "i am" or "ik ben". 
Note: Bot didn't crash for me on the master, so not completely sure if this completely fixes the crash or if i missed something.
=> Fixed issue, bot won't reply to an empty i am/ik ben

package.json, yarn.lock
=> feat: add tsx for faster development

src/commands/MockifyCommand.ts, src/index.ts
=> feat: create spongebob mockify command

package.json, src/commands/UwuCommand.ts, src/index.ts, yarn.lock
Added the uwu command to UwUify a provided sentence
Shamelessly copied from https://github.com/Joehoel/compagnon/blob/master/src/commands/fun/uwu.ts
=> feat(uwucommand): added uwu command

.env.example, src/Bot.ts, src/events/UpvoteEvent.ts, src/events/meme/BangerEvent.ts, src/index.ts, yarn.lock
Added the quality content corner. When a message reaches 5 reactions of a specified emoji (defaults to upvote) it will send the message in a specified channel. The amount of reactions, emoji name and channel to send the message in can be set in the `.env`.
=> feat: quality content corner

src/events/meme/IAmDadEvent.ts, src/events/meme/KabelbaanNoobEvent.ts, src/index.ts, yarn.lock
Have the bot reply with the noob emoji everytime kabelbaan uses it. A highly needed event!
=> feat: Kabelbaan noob event

src/events/UpvoteEvent.ts
@rickklaasboer will update the readme in another pull
=> fix: fixed the upvote event throwing an error

src/commands/meme/MotivationalQuoteCommand.ts, src/index.ts
Adds a command that turns the input into a motivational picture.
Picture is currently grayscaled and blurred in order to improve text visibility.
=> feat: Motivational Quote command

.env.example, README.md, package.json, src/commands/misc/AdventOfCodeCommand.ts, src/index.ts, yarn.lock
=> feat: aoc leaderboard command

src/commands/misc/AdventOfCodeCommand.ts
=> fix: aoc leaderboard sorting and removed cache

src/events/karma/KarmaMessageCreateEvent.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/70
=> fix: only fire karma event when message includes embed

src/events/meme/IAmDadEvent.ts, src/lang/en.json, src/lang/nl.json, src/util/localization.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/60
=> fix: use localization for i am dad event

src/events/karma/KarmaMessageCreateEvent.ts, src/util/misc.ts
=> fix: the previous fix

src/commands/karma/KarmaLeaderboardGetCommand.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/86
=> fix: karma leaderboard command throws error on invalid user id

src/commands/HelpCommand.ts, src/commands/karma/KarmaChannelDisableCommand.ts, src/commands/karma/KarmaChannelEnableCommand.ts, src/commands/karma/KarmaLeaderboardGetCommand.ts, src/commands/karma/KarmaUserGetCommand.ts, src/commands/karma/KarmaUserResetCommand.ts, src/commands/meme/MarieKondoCommand.ts, src/commands/meme/SpooktoberCommand.ts, src/commands/meme/WhereMemeCommand.ts, src/commands/misc/AdventOfCodeCommand.ts, src/commands/text/UwuCommand.ts, src/index.ts, src/lang/en.json, src/lang/nl.json, src/util/PollBuilder.ts
Entire files seem to be editied due to line ending settings
Fixes https://github.com/rickklaasboer/wego-overseer/issues/85
=> refactor: localize all the things

src/events/karma/KarmaMessageCreateEvent.ts, src/util/misc.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/89
=> fix: add url check to karma detection event

README.md, knexfile.ts, src/Bot.ts, src/commands/Command.ts, src/commands/HelpCommand.ts, src/commands/index.ts, src/commands/karma/KarmaCommand/index.ts, src/commands/karma/KarmaLeaderboardGetCommand.ts, src/commands/meme/SpooktoberCommand.ts, src/commands/misc/AdventOfCodeCommand.ts, src/events/Event.ts, src/events/UpvoteEvent.ts, src/events/index.ts, src/events/karma/KarmaDownvoteEvent.ts, src/events/karma/KarmaMessageCreateEvent.ts, src/events/karma/KarmaRemoveDownvoteEvent.ts, src/events/karma/KarmaRemoveUpvoteEvent.ts, src/events/karma/KarmaUpvoteEvent.ts, src/events/meme/BangerEvent.ts, src/events/meme/IAmDadEvent.ts, src/events/meme/KabelbaanNoobEvent.ts, src/events/poll/ReceiveVoteEvent.ts, src/index.ts, src/util/environment.ts
=> refactor(🧹): bulldoze all the messy code

src/commands/misc/HelpCommand.ts, src/lang/en.json, src/lang/nl.json
Help command contents would be > 2000 chars 🤷‍♂️ 
```
DiscordAPIError[50035]: Invalid Form Body
data.content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length.
```
=> fix: add pagination to help command

src/commands/index.ts, src/commands/misc/LightshotCommand.ts
=> feat: add command to generate random lightshot urls

src/events/index.ts, src/events/meme/BiBaBussinEvent.ts
=> feat: bi ba bussin event

package.json, src/commands/music/MusicClearCommand.ts, src/commands/music/MusicCommand/index.ts, src/commands/music/MusicNextCommand.ts, src/commands/music/MusicNowCommand.ts, src/commands/music/MusicPauseCommand.ts, src/commands/music/MusicPlayCommand.ts, src/commands/music/MusicPrevCommand.ts, src/commands/music/MusicQueueCommand.ts, src/commands/music/MusicResumeCommand.ts, src/commands/music/MusicSeekCommand.ts, src/commands/music/MusicSkipCommand.ts, src/commands/music/MusicStopCommand.ts, src/events/music/MusicQueueButtonEvent.ts, yarn.lock
Closes https://github.com/rickklaasboer/wego-overseer/issues/104, https://github.com/rickklaasboer/wego-overseer/issues/102 and https://github.com/rickklaasboer/wego-overseer/issues/101
=> fix(deps): upgrade to discord-player v6

src/commands/misc/LightshotCommand.ts
Closes https://github.com/rickklaasboer/wego-overseer/issues/119
Small refactor
=> refactor: use reply instead of followup

src/commands/birthday/BirthdayCalendarCommand.ts, src/commands/birthday/BirthdayGetCommand.ts, src/commands/birthday/BirthdaySetCommand.ts, src/commands/birthday/BirthdayUpcomingCommand.ts, src/commands/birthday/index.ts, src/lang/en.json, src/lang/nl.json, src/util/timestamp.ts
Reworked the birthday command
The calendar is now sorted properly. Also shows how long until someone's birthday.
Updated several messages to proper date format
Added proper user feedback
Made calendar views consistent
Isn't it lovely how the branch name and the pull request name match?
=> refactor: rework birthday command

src/commands/EntryPointCommand.ts, src/commands/music/MusicCommand.ts
Closes https://github.com/rickklaasboer/wego-overseer/issues/194
=> fix(#194): make music command parameters required

src/events/index.ts, src/events/meme/YoloSwag.ts
=> ewaja feet: yoloswag

src/events/index.ts, src/events/meme/CrazyEvent.ts
=> feat: crazy event

src/events/index.ts
=> fix: activate crazy event

src/commands/music/MusicPlayCommand.ts, src/lang/en.json, src/lang/nl.json
Fixes https://github.com/rickklaasboer/wego-overseer/issues/143
=> fix(#143): incorrect translation when queueing songs

README.md
=> docs(readme): add workflow badges to readme

src/Bot.ts
Most likely fixes the bot timing out on discord api/websocket errors.
=> fix: register error handler on boot

src/commands/Command.ts, src/commands/EntryPointCommand.ts, src/commands/meme/DeepFryCommand.ts, src/commands/meme/DrakeMemeCommand.ts, src/commands/meme/JokeMemeCommand.ts, src/commands/meme/MarieKondoCommand.ts, src/commands/meme/MotivationalQuoteCommand.ts, src/commands/meme/WhereMemeCommand.ts, src/commands/meme/WinnovationMemeCommand.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/265
=> fix: winnovation command crashes bot

src/commands/Command.ts, src/commands/EntryPointCommand.ts, src/commands/karma/KarmaCommand/index.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/144
=> fix: overseer crash when music fails to stream

src/jobs/birthday/BirthdayJob.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/272
=> fix: check if user is in memberlist before sending birthday message

package.json, yarn.lock
update discord-player deps. I hate you dependabot.
=> fix: update discord player deps

src/app/commands/misc/QualityContentLeaderboardCommand.ts, src/config/app.ts
=> fix: rename ccleaderboard to qcleaderboard

src/app/events/meme/BangerEvent.ts
=> refactor: decrease chance of banger

src/app/commands/BaseEntrypointCommand.ts, src/handlers/CommandHandler.ts, src/handlers/EventHandler.ts, src/lang/en.json, src/lang/nl.json, src/util/errors/AuthorizationError.ts, src/util/misc/discord.ts
=> fix: make sure authorization errors are handled accordingly

package.json, src/app/events/meme/BangerEvent.ts, src/app/jobs/youtube/YouTubeSQSPollJob.ts, src/app/services/aws/ComprehendService.ts, src/app/services/aws/SQSService.ts, yarn.lock
Fixes https://github.com/rickklaasboer/wego-overseer/issues/379
=> fix: use comprehend to detect dominant language before firing bang event

.env.example, src/app/commands/karma/KarmaUserGraphCommand.ts, src/app/events/karma/KarmaDownvoteEvent.ts, src/app/events/karma/KarmaMessageCreateEvent/index.ts, src/app/events/karma/KarmaRemoveDownvoteEvent.ts, src/app/events/karma/KarmaRemoveUpvoteEvent.ts, src/app/events/karma/KarmaUpvoteEvent.ts, src/app/services/graph/GraphService.ts, src/config/misc.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/332
=> refactor: make karma emoji names configurable

src/app.ts, src/app/events/misc/QualityContentUpvoteEvent.ts, src/app/events/misc/TrashContentDownvoteEvent.ts
Fixes https://github.com/rickklaasboer/wego-overseer/issues/277
=> feat: quality content timer

src/app/commands/birthday/BirthdayGetCommand.ts, src/lang/en.json, src/lang/nl.json
Added a specific message when someone uses `/birthday get user` and that user's birthday is today.
haven't tested it. so that still needs to be done. or not, idc.
=> feat: added message for today's birthday on birthday get

.env.example, src/app/jobs/HeartbeatJob.ts, src/config/app.ts, src/config/misc.ts
=> feat: add heartbeat job
